#!/usr/bin/env bash
# shellcheck disable=SC2086
set -e

## Description: Initialize TYPO3 installation
## Usage: init-typo3
## Example: ddev init-typo3

readonly dbHost="db"
readonly dbUser="db"
readonly dbPassword="db"
readonly dbName="db"
readonly dbCredentials="-h${dbHost} -u${dbUser} -p${dbPassword}"
readonly fixturePath="/var/www/html/Tests/Fixtures"
readonly typo3Binary="/var/www/html/vendor/bin/typo3"

function _progress() {
    printf "%s... " "$1"
}

function _done() {
    printf "\e[32mDone\e[39m\n"
}

# Create empty database
_progress "Creating empty database"
mysql -Nse "SHOW TABLES" $dbCredentials "$dbName" | while read -r table; do
    mysql -e "DROP TABLE ${table}" $dbCredentials "$dbName"
done
_done

# Prepare setup environment
export TYPO3_DB_DRIVER=mysqli
export TYPO3_DB_USERNAME="$dbUser"
export TYPO3_DB_PASSWORD="$dbPassword"
export TYPO3_DB_PORT=3306
export TYPO3_DB_HOST="$dbHost"
export TYPO3_DB_DBNAME="$dbName"
export TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
export TYPO3_SETUP_ADMIN_USERNAME=admin
export TYPO3_SETUP_ADMIN_PASSWORD=Passw0rd!
export TYPO3_SERVER_TYPE=other
export TYPO3_PROJECT_NAME="EXT:bw_jsoneditor"

# Set up environment
_progress "Setting up TYPO3 installation"
"$typo3Binary" setup --no-interaction --force --quiet
_done

# Patch entry points to include c3.php for code coverage
_progress "Patching entry points for code coverage"
if ! grep -q 'c3.php' /var/www/html/public/index.php; then
    sed -i '1,/^<?php/s/^<?php/<?php\n\nif (file_exists(dirname(__DIR__) . "\/c3.php")) {\n    include dirname(__DIR__) . "\/c3.php";\n}\n/' /var/www/html/public/index.php
fi
if ! grep -q 'c3.php' /var/www/html/public/typo3/index.php; then
    sed -i '1,/^<?php/s/^<?php/<?php\n\nif (file_exists(dirname(dirname(__DIR__)) . "\/c3.php")) {\n    include dirname(dirname(__DIR__)) . "\/c3.php";\n}\n/' /var/www/html/public/typo3/index.php
fi
_done

# Set extension configuration
_progress "Setting up configuration"
"$typo3Binary" configuration:set SYS/trustedHostsPattern '.*.*' --no-interaction --quiet
"$typo3Binary" cache:flush
_done

# Import DB fixtures
for file in "$fixturePath"/*.sql; do
    _progress "Importing DB fixture \"$(basename "$file")\""
    mysql $dbCredentials "$dbName" < "$file"
    _done
done
